name: Build and release

on:
  push:
    tags:
      - v*


jobs:
  build:
    name: "Build and Release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # We fetch to 0 so we can collect the commits
      # since last update
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build project
        run: npm run release

      - name: Zip release
        run: |
          cd release && zip -r ../mojito_pdm.zip .
          
      - name: Create and Upload Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: mojito_pdm.zip
